require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/**/*
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Rails/HasAndBelongsToMany:
  Enabled: false
