version: '3.7'

services:
  product-list-app:
    build: .
    container_name: product-list-app
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: development
    volumes:
      - .:/ruby/product-list-app
    restart: on-failure
